"""
agent_skills.py — Per-project Skills.md auto-detect + read/write.

Skills.md lives at the project root (next to CLAUDE.md, GUIDE.md). It has two
sections:

    User section  — human-authored notes, preserved across refreshes.
    Auto section  — bullets + JSON block, regenerated by detect_skills().

The file is also mirrored into the SQLite `project_skills` table so the
WebApp can query it without parsing markdown.
"""
from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

import agent_db as db


# ── File constants ────────────────────────────────────────────────────────────

SKILLS_FILENAME     = 'Skills.md'
AUTO_SECTION_MARKER = '## Auto-Detected Capabilities'
DO_NOT_EDIT_MARKER  = '<!-- SuperAgent fills this section. Do not edit below this line. -->'

# Detection heuristics ────────────────────────────────────────────────────────
# Patterns require actual import/usage syntax to avoid false positives from
# docs/READMEs mentioning frameworks in passing.
FRAMEWORK_PATTERNS: list[tuple[str, str]] = [
    (r'(?:from\s+flask\b|import\s+flask\b)',           'Flask'),
    (r'(?:from\s+fastapi\b|import\s+fastapi\b)',       'FastAPI'),
    (r'(?:from\s+django\b|import\s+django\b)',         'Django'),
    (r'(?:from\s+sqlalchemy\b|import\s+sqlalchemy\b)', 'SQLAlchemy'),
    (r'(?:from\s+pydantic\b|import\s+pydantic\b)',     'Pydantic'),
    (r'''from\s+["']react["']|require\(["']react["']\)''',          'React'),
    (r'''from\s+["']vue["']|new\s+Vue\s*\(''',                       'Vue'),
    (r'''from\s+["']next/|require\(["']next/''',                     'Next.js'),
    (r'\btailwindcss\b',                                            'TailwindCSS'),
    (r'(?:from\s+anthropic\b|import\s+anthropic\b)',                'Anthropic SDK'),
    (r'(?:from\s+mistralai\b|import\s+mistralai\b)',                'Mistral SDK'),
    (r'(?:from\s+openai\b|import\s+openai\b)',                      'OpenAI SDK'),
    (r'from\s+google\.generativeai\b|import\s+google\.generativeai\b','Google Gemini SDK'),
    (r'(?:from\s+langchain\b|import\s+langchain\b)',                'LangChain'),
    (r'(?:from\s+requests\b|import\s+requests\b|import\s+httpx\b)', 'HTTP client'),
    (r'(?:import\s+sqlite3\b|sqlite3\.connect\s*\()',               'SQLite'),
    (r'(?:import\s+psycopg2\b|postgresql://|postgres://)',          'PostgreSQL'),
    (r'(?:import\s+redis\b|redis\.Redis\s*\()',                     'Redis'),
]

# Files used for content-based framework detection. Markdown / RTF / plain
# text are excluded — they mention frameworks in passing and produce noise.
CODE_EXTS = {
    '.py', '.js', '.ts', '.tsx', '.jsx', '.go', '.rs', '.java',
    '.sh', '.html', '.css', '.sql', '.json', '.toml', '.yaml', '.yml',
}

LANGUAGE_BY_EXT: dict[str, str] = {
    '.py':   'Python',
    '.js':   'JavaScript',
    '.ts':   'TypeScript',
    '.tsx':  'TypeScript (React)',
    '.jsx':  'JavaScript (React)',
    '.go':   'Go',
    '.rs':   'Rust',
    '.java': 'Java',
    '.sh':   'Shell',
    '.html': 'HTML',
    '.css':  'CSS',
    '.sql':  'SQL',
}

TEXT_EXTS = {
    '.py', '.js', '.ts', '.tsx', '.jsx', '.go', '.rs', '.java',
    '.sh', '.html', '.css', '.md', '.yaml', '.yml', '.json',
    '.toml', '.txt', '.cfg', '.ini', '.sql',
}

# Files we never bother reading for content scans
SKIP_DIRS = {'__pycache__', '.git', 'node_modules', '.venv', 'venv', 'dist', 'build', 'Artifacts'}

MAX_FILE_BYTES = 100_000   # don't slurp huge files
MAX_FILES      = 500       # cap on per-project scan


# ── Detection ─────────────────────────────────────────────────────────────────

def _iter_project_files(project_path: str):
    """Yield Path objects for text files in the project, skipping noise dirs.
    The detector's own module is skipped because its regex source contains
    every pattern string by construction.
    """
    base = Path(project_path)
    if not base.is_dir():
        return
    self_path = Path(__file__).resolve()
    count = 0
    for root, dirs, files in os.walk(base):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.startswith('.')]
        for name in files:
            ext = os.path.splitext(name)[1].lower()
            if ext not in TEXT_EXTS:
                continue
            full = Path(root) / name
            try:
                if full.resolve() == self_path:
                    continue
            except OSError:
                pass
            yield full
            count += 1
            if count >= MAX_FILES:
                return


def detect_skills(project_path: str) -> dict:
    """Scan a project directory and return a detected-skills dict.

    Returns:
        {
            'languages':  ['Python', ...],
            'frameworks': ['Flask', ...],
            'ai_models':  ['Anthropic SDK', ...],
            'infra':      ['SQLite', ...],
            'patterns':   ['REST API', ...],
        }
    """
    languages: dict[str, int] = {}
    frameworks: set[str] = set()
    ai_models:  set[str] = set()
    infra:      set[str] = set()
    seen_filenames: set[str] = set()

    files = list(_iter_project_files(project_path))

    for f in files:
        seen_filenames.add(f.name.lower())
        ext = f.suffix.lower()
        lang = LANGUAGE_BY_EXT.get(ext)
        if lang:
            languages[lang] = languages.get(lang, 0) + 1

        if ext not in CODE_EXTS:
            continue  # skip docs/markdown for content-based detection

        try:
            if f.stat().st_size > MAX_FILE_BYTES:
                continue
            content = f.read_text(encoding='utf-8', errors='ignore')
        except OSError:
            continue

        for pattern, label in FRAMEWORK_PATTERNS:
            if re.search(pattern, content):
                if label.endswith('SDK') or label in ('LangChain',):
                    ai_models.add(label)
                elif label in ('SQLite', 'PostgreSQL', 'Redis'):
                    infra.add(label)
                else:
                    frameworks.add(label)

    # Filename-based infra checks
    if 'dockerfile' in seen_filenames:
        infra.add('Docker')
    if any(n in seen_filenames for n in ('docker-compose.yml', 'docker-compose.yaml', 'compose.yml')):
        infra.add('Docker Compose')
    if any(n.endswith('.db') or n.endswith('.sqlite') for n in seen_filenames):
        infra.add('SQLite')

    # Patterns inferred from filenames + detected frameworks
    patterns: list[str] = []
    if 'Flask' in frameworks or 'FastAPI' in frameworks or 'Django' in frameworks:
        patterns.append('REST API')
    if any(f.suffix == '.html' for f in files):
        patterns.append('Web dashboard / HTML UI')
    if 'SQLite' in infra:
        patterns.append('DB-first state (SQLite)')
    if any(f.name.endswith('.memory.md') for f in files):
        patterns.append('SuperAgent memory files')

    # Languages sorted by file-count desc, then alpha
    languages_sorted = [
        lang for lang, _ in sorted(languages.items(), key=lambda x: (-x[1], x[0]))
    ]

    return {
        'languages':  languages_sorted,
        'frameworks': sorted(frameworks),
        'ai_models':  sorted(ai_models),
        'infra':      sorted(infra),
        'patterns':   patterns,
    }


# ── Skills.md read / write ────────────────────────────────────────────────────

def _skills_path(project_path: str) -> Path:
    return Path(project_path) / SKILLS_FILENAME


def read_skills(project_path: str) -> dict:
    """Return current Skills.md state:
        {'exists': bool, 'raw': str, 'user_section': str, 'auto': dict}
    The 'auto' dict is parsed back from the embedded JSON block.
    """
    path = _skills_path(project_path)
    if not path.exists():
        return {'exists': False, 'raw': '', 'user_section': '', 'auto': {}}

    raw = path.read_text(encoding='utf-8', errors='ignore')
    idx = raw.find(AUTO_SECTION_MARKER)
    if idx == -1:
        return {'exists': True, 'raw': raw, 'user_section': raw, 'auto': {}}

    user_section = raw[:idx].rstrip()
    auto_section = raw[idx:]
    auto_data: dict = {}
    json_match = re.search(r'```json\s*(\{.*?\})\s*```', auto_section, re.DOTALL)
    if json_match:
        try:
            auto_data = json.loads(json_match.group(1))
        except json.JSONDecodeError:
            pass
    return {'exists': True, 'raw': raw, 'user_section': user_section, 'auto': auto_data}


def _bullets(items: list[str]) -> str:
    return '\n'.join(f'- {i}' for i in items) if items else '- _(none detected)_'


def generate_skills_md(project_name: str, detected: dict, user_section: str = '') -> str:
    """Build the full Skills.md content: user section + auto section."""
    now = datetime.now(timezone.utc).isoformat(timespec='seconds')

    if not user_section.strip():
        user_section = (
            f'# Skills — {project_name}\n\n'
            '> Auto-detected by SuperAgent. Edit the user sections below freely; '
            'changes survive `Refresh`.\n\n'
            '## Language & Runtime\n'
            '- <!-- e.g. Python 3.11, Node 20 -->\n\n'
            '## Frameworks & Libraries\n'
            '- <!-- e.g. Flask, React, SQLAlchemy -->\n\n'
            '## AI / Model Usage\n'
            '- <!-- e.g. Claude Sonnet 4.6 (primary), Mistral Large (review) -->\n\n'
            '## Infrastructure\n'
            '- <!-- e.g. SQLite, Docker, port 8001 -->\n\n'
            '## Key Patterns\n'
            '- <!-- e.g. REST API, DB-first state -->\n\n'
            '## Constraints\n'
            '- <!-- e.g. No external DB, single-file Flask app -->'
        ).rstrip()

    auto = (
        f'\n\n{AUTO_SECTION_MARKER}\n'
        f'{DO_NOT_EDIT_MARKER}\n'
        f'> Refreshed: {now}\n\n'
        f'### Languages\n{_bullets(detected.get("languages", []))}\n\n'
        f'### Frameworks & Libraries\n{_bullets(detected.get("frameworks", []))}\n\n'
        f'### AI / Model SDKs\n{_bullets(detected.get("ai_models", []))}\n\n'
        f'### Infrastructure\n{_bullets(detected.get("infra", []))}\n\n'
        f'### Detected Patterns\n{_bullets(detected.get("patterns", []))}\n\n'
        '```json\n'
        f'{json.dumps(detected, indent=2)}\n'
        '```\n'
    )
    return user_section.rstrip() + auto


def write_skills(project_path: str, project_name: str, detected: dict) -> str:
    """Write/refresh Skills.md, preserving any existing user section.
    Returns the absolute path written.
    """
    existing = read_skills(project_path)
    user_section = existing['user_section'] if existing['exists'] else ''
    content = generate_skills_md(project_name, detected, user_section=user_section)
    path = _skills_path(project_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')
    return str(path)


def refresh_skills(project_id: int, project_path: str, project_name: str) -> dict:
    """Detect → write Skills.md → mirror into DB. Returns:
        {'path': str, 'detected': dict}
    """
    detected = detect_skills(project_path)
    path = write_skills(project_path, project_name, detected)
    db.save_project_skills(project_id, detected)
    return {'path': path, 'detected': detected}


# ── Prompt-context helper ─────────────────────────────────────────────────────

def skills_context_summary(project_path: str) -> str:
    """Compact, one-liner-per-category string for injection into prompts.
    Falls back to running detection if Skills.md hasn't been written yet.
    """
    data = read_skills(project_path).get('auto') or {}
    if not data:
        data = detect_skills(project_path)

    lines: list[str] = []
    if data.get('languages'):
        lines.append('Languages: ' + ', '.join(data['languages'][:5]))
    if data.get('frameworks'):
        lines.append('Frameworks: ' + ', '.join(data['frameworks'][:6]))
    if data.get('ai_models'):
        lines.append('AI SDKs: '    + ', '.join(data['ai_models']))
    if data.get('infra'):
        lines.append('Infra: '      + ', '.join(data['infra']))
    if data.get('patterns'):
        lines.append('Patterns: '   + ', '.join(data['patterns']))
    return '\n'.join(lines)
